/*
    
    UN JOVEN MUY AFORTUNADO LOGRO GANAR EL PRIMERO PREMIO DE LA LOTERIA...EXACTO, ESTAMOS HABLANDO DE UN VAGABUNDO, AL QUE COFLA LE DIO UNA MANO, ESTE POBRE DECIDE HACER UNA FIESTA PARA FESTEJAR QUE SALIO DE LA POBREZA CON ESTE MILLONARIO COMPRO UNA MAQUINA QUE DEJA PARAR A LOS MAYORES DE EDAD, ENTRE OTRA COSAS

    SOLUCIONES
    1.  DEJAR PASAR A SOLOS MAYORES DE EDAD
    2.  LA PRIMER PERSONA QUE ENTRE DESPUES DE LAS 2AM, NO PAGA
    
*/