/*
    1-  MOSTRAR LAS PARTICULARIDADES DE LOS CELULARES
    2-  CADA UNO DEBE DE TENER COLOR, PESO, RESOLUCION DE PANTALLA, CAMARA Y MEMORIA RAM
    3-  DEBEN DE PODER ENCENDER, REINICIAR, TOMAR FOTO Y GRABAR´
    
*/