//  TERMINO EL PRIMER SEMESTRE Y COFLA NO SABE SI APROBARA O NO LAS MATERIAS, PARA LOGRARLO NECESITARA CONTAR CON AL MENOS EL 90% DE ASISTENCIA, EL PROMEDIO POR LA MATERIA DEBE SER DE AL MENOS 7 DEBE TENER AL MENOR EL 70% DE LOS TRBAJOS PRACTICOS ENTREGADOS

//  SOLICITAR LOS DATOS Y DECIRLE SI APRUEBA O NO
//  MOSTRAR TODO ESTO CON COLORES REPRESENTATIVO
//  TODO ESTO ESTRUCTURADO COMO TABLA   

