/* 
    COFLA VUELVE DE LA COMISARIA EXAUSTO Y POR LO TANTO CANSADO QUE ESTABA SE FUE A DORMIR... AL OTRO DIA COMIENZAN LAS CLASES DEL CICLO BASICO DE LA UNIVERSIDAD (PORQUE COFLA QUIERE SER PROGRAMADOR Y SE INSCRIBIO EN LA FACULTDADDE INGENIERA PARA ESTUDIAR EL DESARROLLO DE SOFTARE). EN SU CURSO EN TOTAL SON 19 ALUMNOS, PERO SUGRIO UN PROBLEMA QUE COMPLICO UN POCO LA FACULTAD: SE ROMPIO EL REGISTRO DEL SISTEMA DE ASISTENCIA Y DURANTE LOS PROXIMOS 30 DIAS NO SE PODRAN HACER REGISTRO DE DATOS DE NINGUN TIPO, POR ENDE LAS CLASES NO PODRAN COMENAR HASTA QUE ESO SE SOLICIONE

    SOLUCIONES
    1.  CREAR UN MINI SISTEMA QUE NOS PERMITA REGISTRAR LOS ALUMNOS QUE ESES PRESENTE Y AUSENTES (P) && (A)
    2.  PASADO LOS 30 DIAS MOSTRAR LA SITUACION FINAL DE TODOS LOS ALUMNOS (NUMERO TOTAL DE P Y A)
    3.  SE PUEDE MAS DE UN MAXIMO DE 10% DE AUSENCIA POR SEMESTRE, SE TIENEN MAS QUE ACLARAR QUE ESTA REPROBADO
    
*/